### ISSUE TITLE
Multiple content types

### ISSUE THREAD

**Issue by t0ker** [nuxt-community/nuxtent#11]
Hi, 

Having some issues with adding multiple content types, 

when i add more than 3 types, it will complain: 

Unhandled promise rejection (rejection id: 2): TypeError: Expected "slug" to match "[^\/]+?", but received "",

and with 3 of them, the first two will try to use the last added template. so keeps failing when going to that specific route. 

How ever can still list them on the product pages just fine, it fetches the permalink, thumbnail and title of that route.

Any ideas of what it could be? 

`module.exports = {
  srcDir: '../content',
  dirs: [
    ['first', {
      routeName: 'first',
      permalink: 'games/:slug',
      isPost: false
    }],
    ['second', {
      routeName: 'second',
      permalink: 'games/:slug',
      isPost: false
    }],
    ['third', {
      routeName: 'third',
      permalink: 'games/:slug',
      isPost: false
    }],
    ['third', {
      routeName: 'tablegame',
      permalink: 'games/:slug',
      isPost: false
    }]
  ]
}`

btw, any good way to nest several types under one main category?

**Comment by alidcastano** [comment]
Hey, @t0ker 

I'm heavily refactoring the design so that all the content isn't in the client bundle and other improvements. 

API will stay mostly the same, but maybe changes will fix error. 

The changes will be pushed by tomorrow, latest. Can you try it then and let me know? 

Also, can you elaborate on your second question – what are you trying to do?

**Comment by t0ker** [comment]
Il wait for the release and try again :) 

few questions until then:

1. Nest content types like parent (calls evertyhing), then nest sub folders that function as "categories". So they can be split and listed nicely.

2. Can several directories point to the same route path?  they are different categories of same type of page. ex. action, drama, comedy directories, that all share the permalink movies/:slug, but use different routenames for use of different templates

3. When adding the code from example into a page, everything works great, but if i want to move that same code into a component it wont fetch the content listed in folders. Is this possible today or am I missing something?

**Comment by alidcastano** [comment]
In response to your questions:

1. Two options: Add the categories to the data and filter the content yourself or nest the content under sub folders - e.g. `content/posts/life/somePost.md` and register the nested directories individually. Usage depends on how often you want the content all grouped together. 
2. Next update will support content templates. So that shouldn't be a problem! Conveniently, that's one of the parts of the API that is changing. :) 
3. That's constraint is because of Nuxt. Only pages have access to `asyncData`. You need to fetch content inside there because that method can be initiated during in the server.

Hopefully, that clarifies things. If you have a specific use case you have in mind, feel free to post how the config would look here. I'm refactoring the design today, so would be happy to discuss it.

**Comment by t0ker** [comment]
Thank you :) Really looking forward to this

**Comment by alidcastano** [comment]
Hey, sorry it's taking so long. Working on documentation site but changes have been ready. Just install `npm install nuxtent`  (changed name!) 

You might run into problems with some slight changes in the API, docs will be up by tonight to aid with that as I still need to fully update `README`.

**Comment by alidcastano** [comment]
Hey, documentation is available at https://nuxtent.now.sh/

Still, some kinks to work out (not mobile yet), so not officially released.  But feel free to try new version. if you need an example check out the code in the docs which uses Nutent.

**Comment by t0ker** [comment]
thanks :) will check it out right away!

Big thanks for update and support :)

**Comment by alidcastano** [comment]
No problem.  I'm closing this issue for now since new version is officially released. Feel free to open it back up or open up a new one if you encounter any problems! 

I've also updated examples and docs, which you can use as guidance.
